# Generated by Django 4.2.4 on 2023-09-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_purchases_sales_remove_sale_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='p_categories', to='stock.product'),
        ),
    ]
